# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 855e2dac464cfeaf337c4f6c911e6ba1bc432ac00e0f6c049b2c9142181eefb92fb27b14818e70f8326cc981b52e4565058d1603268ff2fe545117e661d53208

test:
  secret_key_base: 66193bc898de5a3096d9b578fe82f964462b8fd453aa8eabefd74b73e3810187211c60eae5d71d244e6333cd75df0bb2275cddd7605f56d8818c94a815af4dd8

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
